### PR TITLE
[FIX] respect mute state when changing volume during mute

### PR DESCRIPTION
**Pull request by othmar52**
fixes  https://github.com/katspaugh/wavesurfer.js/issues/2502

### CODE REVIEW

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks @othmar52, can you also add a unit test for this? And use 6.2.0 in changelog instead.

**Comment by othmar52** [comment]
> thanks @othmar52, can you also add a unit test for this?  

Unfortunately i don't know how to do this.  
Do you have any commit-hash that adds a unit test for a bugfix in the wavesurfer repo? Case yes i can take a look and give it a try...

**Comment by othmar52** [comment]
@thijstriemstra  Thank you for the link!  
I will take a look and try to add a unit test.  But i am unsure which behaviour should be forced.  
In my opinion the current behaviour (without my changes) is **not correct**:  
image  
i think `getVolume()` should always return the actual or saved volume no matter if the audio is muted or not.  
Do you agree or do you think `getVolume()` should always return `0` when muted?

**Review by katspaugh — APPROVED** [review]
I suggest we merge this w/o tests for now since the code is pretty trivial.

**Pull request merged**
