### PR TITLE
Fix: NPM publish in the CI job

### LINKED ISSUE #2723: Fix the automatic publishing on NPM
The script that published the NPM package is broken after #2710.

https://github.com/wavesurfer-js/wavesurfer.js/actions/runs/4419688300/jobs/7748430370

Looks like this part was necessary after all:

```
      - uses: actions/setup-node@v3
         with:
           node-version: 16
           registry-url: https://registry.npmjs.org/
```

### PR DESCRIPTION
**Pull request by katspaugh**
Resolves #2723.

I've fixed it by adding npm install. Tested by triggering the action on this branch and publishing with `--dry-run`. ✅

### CODE REVIEW

**Comment by thijstriemstra** [comment]
> Tested by triggering the action on this branch and publishing with --dry-run.

Do you have a link to the results?

**Comment by katspaugh** [comment]
https://github.com/wavesurfer-js/wavesurfer.js/actions/runs/4439559664/jobs/7792182228

**Comment by thijstriemstra** [comment]
```
npm notice === Tarball Details === 
npm notice name:          wavesurfer.js                           
npm notice version:       6.6.1                                   
npm notice filename:      wavesurfer.js-6.6.1.tgz                 
npm notice package size:  492.5 kB                                
npm notice unpacked size: 2.3 MB                                  
npm notice shasum:        eb5d57f4092327c10d1e7e9d925200e51348d6b1
npm notice integrity:     sha512-HovaDsrqTbkuY[...]LHgoMKqXQlLjQ==
npm notice total files:   86                                      
npm notice 
npm WARN This command requires you to be logged in to https://registry.npmjs.org/ (dry-run)
npm notice Publishing to https://registry.npmjs.org/ with tag latest and default access (dry-run)
+ wavesurfer.js@6.6.1
```

Looks good. The not logged in thing is weird though, why does it raise this warning when doing a dry run? Are we sure the same won't happen when doing an actual release?

**Comment by katspaugh** [comment]
No idea

**Comment by katspaugh** [comment]
Thanks for the checking this with me @thijstriemstra.
I’m gonna merge this now, hopefully it will work with the next release.

**Comment by thijstriemstra** [comment]
> hopefully it will work with the next release.

Unfortunately, the build is still failing: https://github.com/wavesurfer-js/wavesurfer.js/actions/runs/4454567892/jobs/7823848198

**Pull request merged**
