### PR TITLE
Chore: improve the release and changelog automation

### PR DESCRIPTION
**Pull request by katspaugh**
### Short description of changes:
I've added a new script and a corresponding NPM command: `yarn release`
This command will automate most of the release routine, you just need to type a new version. See more details in the update readme.

### Related Issues and other PRs:
Discussion: https://github.com/wavesurfer-js/wavesurfer.js/discussions/2692

### CODE REVIEW

**Comment by katspaugh** [comment]
Tested while creating #2715.
I had to fine-tune a few things, but it seems work well now.
wdyt @thijstriemstra?

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
thanks for this @katspaugh 

Since we're a cross-platform, nodejs project I would like the release script to use node as well so it runs on all platforms and is easier to maintain and readable by any nodejs dev wanting to contribute.

**Comment by katspaugh** [comment]
@thijstriemstra no, sorry, I'm not going to redo it in Node.
I think bash scripts are pretty ubiquitous in web development, and it's no different from, say, our GitHub Actions scripts.
There are plenty of ways to have a [Unix-like environment on windows](https://itsfoss.com/run-linux-commands-in-windows/), and this script should work w/o modification on most flavors of Unix and Linux, including the Mac.

**Comment by thijstriemstra** [comment]
> should work w/o modification on most flavors of Unix and Linux, including the Mac.

If it works on Linux and Mac, I'm ok with it. Perhaps we should discuss how to approach these scripts first in the future?

**Comment by katspaugh** [comment]
Absolutely, I’m open to discussions.

**Review by thijstriemstra — CHANGES_REQUESTED** [review]
The script should fail on any errors, see https://intoli.com/blog/exit-on-errors-in-bash-scripts/

**Comment by sundayz** [comment]
> @thijstriemstra no, sorry, I'm not going to redo it in Node.
> I think bash scripts are pretty ubiquitous in web development, and it's no different from, say, our GitHub Actions scripts.
> There are plenty of ways to have a [Unix-like environment on windows](https://itsfoss.com/run-linux-commands-in-windows/), and this script should work w/o modification on most flavors of Unix and Linux, including the Mac.

sounds like we should set up docker for development/CI for this project?

**Comment by katspaugh** [comment]
I don’t see the need right now, Node apps are typically very easy to run on a host machine. It’s not some complicated toolchain or infra.
This script in particular is just a bunch of git commands.

**Review by thijstriemstra — APPROVED** [review]

**Comment by thijstriemstra** [comment]
@katspaugh the script/implentation seems to cause issues: https://github.com/wavesurfer-js/wavesurfer.js/actions/runs/4405675719/jobs/7716869005

**Comment by katspaugh** [comment]
It failed because 6.5.2 didn't have a tag. I published it to npm but forgot to tag it. I've tagged it now.
This was an exceptional case because I had to publish 6.5.2 quickly due to the accidental alpha publish.
In the normal process, if we use the release script, it should work as expected.

**Pull request merged**
